version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: moneyControl-app
    ports:
      - '3005:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: moneyControl-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=moneyControl

  pgadmin:
    image: dpage/pgadmin4
    container_name: moneyControl-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db
